update 1-eks-cluster-with-new-vpc example with provider configuration
aws-samples/aws-eks-accelerator-for-terraform pull request #163
Opened 2021-12-29 18:34 UTC by askulkarni2

*Issue #, if available:* #156

*Description of changes:*

We are removing `providers.tf` as per module convention and updating our examples to show how consumer modules can provide us with their `provider {}` configurations. 

Tests:

Apply
```
terraform  apply -auto-approve
...
...
module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Still creating... [15m0s elapsed]
module.kubernetes-addons.module.aws_coredns[0].aws_eks_addon.coredns: Creation complete after 15m7s [id=aws001-preprod-dev-eks:coredns]

Apply complete! Resources: 78 added, 0 changed, 0 destroyed.
```

Destroy
```
terraform destroy -auto-approve
...
...
module.aws_vpc.aws_vpc.this[0]: Destruction complete after 1s
module.aws-eks-accelerator-for-terraform.module.aws_eks.aws_iam_role.cluster[0]: Destruction complete after 2s

Destroy complete! Resources: 78 destroyed.
```  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-29 18:51 UTC, kcoleman731 commented
@askulkarni2 don't you want to pass providers to the modules? I.E. here? https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/task/update-examples-for-providers/deploy/1-eks-cluster-with-new-vpc/main.tf

2021-12-29 19:03 UTC, askulkarni2 commented
> @askulkarni2 don't you want to pass providers to the modules? I.E. here? https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/task/update-examples-for-providers/deploy/1-eks-cluster-with-new-vpc/main.tf

@kcoleman731 doesn't look like we need to add that.

2021-12-29 19:25 UTC, vara-bonthu requested changes
One change requested just to avoid conflicts on next PR

2021-12-29 19:25 UTC, vara-bonthu commented on deploy/2-eks-cluster-with-import-vpc/eks/main.tf
> +}
I changed this file heavily with my new PR. May be you can revoke the change to this file.

2021-12-29 19:27 UTC, vara-bonthu commented
> @askulkarni2 don't you want to pass providers to the modules? I.E. here? https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/task/update-examples-for-providers/deploy/1-eks-cluster-with-new-vpc/main.tf

It's not required as per Terraform Docs. Provider config is only required in root module. All the sub modules will leverage the same provider defined in the root.

2021-12-30 00:54 UTC, kcoleman731 commented
Implicit Provider Inheritance https://www.terraform.io/language/modules/develop/providers#implicit-provider-inheritance

2021-12-30 04:13 UTC, kcoleman731 approved these changes

2021-12-30 10:49 UTC, vara-bonthu requested changes
One small change required and it can be merged after

2021-12-30 10:49 UTC, vara-bonthu commented on deploy/1-eks-cluster-with-new-vpc/main.tf
> +  depends_on = [module.aws-eks-accelerator-for-terraform]
@askulkarni2 We may need to change this to this line based in our recent timing issues. `depends_on = [module.aws-eks-accelerator-for-terraform.managed_node_groups]`

2021-12-31 11:30 UTC, merged