Bugfix/plan time
aws-samples/aws-eks-accelerator-for-terraform pull request #165
Opened 2021-12-29 21:36 UTC by kcoleman731

*Issue #, if available:*

*Description of changes:*

Optimizing TF plan time. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-29 22:30 UTC, askulkarni2 approved these changes

2021-12-29 23:11 UTC, vara-bonthu requested changes
One change required

2021-12-29 23:11 UTC, vara-bonthu commented on modules/irsa/data.tf
> +      variable = "${var.eks_oidc_issuer_url}:sub"
This should be `variable = "${replace(var.eks_oidc_issuer_url, "https://", "")}:sub"`

2021-12-30 14:49 UTC, vara-bonthu requested changes
I think we figured out the issue is due to `depends_on` on module causing the delays. Do we still need this approach? Just to reduce passing too many variables for each add-on.

2021-12-30 14:49 UTC, vara-bonthu commented on modules/irsa/outputs.tf
> +  value       = ""
Is this correct for output variable?

2021-12-30 14:49 UTC, vara-bonthu commented on modules/irsa/outputs.tf
> +  value       = ""
same as above

2022-01-04 22:48 UTC, closed without merging