Doc/extension guide
aws-samples/aws-eks-accelerator-for-terraform pull request #265
Opened 2022-02-17 06:25 UTC by askulkarni2

### What does this PR do?

Creates a new Extensibility guide for Customers and Partners to provide their add-ons via the framework.

### Motivation

We want to provide a way for customers and partners to be able easily extend the framework so add-ons can be quickly added outside of the core repo.

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [X] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [X] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-02-17 12:42 UTC, vara-bonthu requested changes
Nice on Apoorva! 👍🏼  
Few minor changes requested

2022-02-17 12:42 UTC, vara-bonthu commented on docs/extensibility.md
> +  set_values        = local.set_values
show `set_sensitive_values` as well here.

2022-02-17 12:42 UTC, vara-bonthu commented on docs/extensibility.md
> +}
We need the following as well

```hcl
variable "kube_state_metrics_irsa_permissions_boundary" {
  type        = string
  default     = ""
  description = "IAM Policy ARN for IRSA IAM role permissions boundary"
}

variable "kube_state_metrics_irsa_policies" {
  type        = list(string)
  default     = []
  description = "IAM policy ARNs for Kube State Metrics IRSA"
}

```

2022-02-17 12:42 UTC, vara-bonthu commented on modules/kubernetes-addons/variables.tf
> +
Add this here

```hcl
variable "kube_state_metrics_irsa_permissions_boundary" {
  type        = string
  default     = ""
  description = "IAM Policy ARN for IRSA IAM role permissions boundary"
}
```

2022-02-17 20:57 UTC, kcoleman731 reviewed
Really nice work here.

2022-02-17 20:57 UTC, kcoleman731 commented on docs/extensibility.md
> +We expect that certain add-ons will need to provide to sensitive values to their helm chart configuration such as password, license keys, API keys, etc. We recommend that you ask customers to store s
provide access to

2022-02-23 22:21 UTC, vara-bonthu approved these changes
LGTM

2022-02-24 21:18 UTC, kcoleman731 reviewed
This looks awesome. Thank you!

2022-02-24 21:18 UTC, merged