make gp3 as the default volume type
aws-samples/aws-eks-accelerator-for-terraform pull request #277
Opened 2022-02-21 22:56 UTC by askulkarni2

### What does this PR do?

Make GP3 as the default volume type for node groups instances.

### Motivation

Customers can save up to 20% on costs by switching to gp3. GP3 is the default type in [`terraform-aws-eks`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a99689cc13147f4afc426b34ba009875a28614e/CHANGELOG.md#v1400---2021-01-29) and in the EBS CSI driver as well. 

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [N/A] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [N/A] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [X] E2E Test successfully complete before merge?

### Additional Notes

2022-02-22 00:12 UTC, kcoleman731 approved these changes

2022-02-22 08:33 UTC, vara-bonthu requested changes
Do you want to change the examples as well?

2022-02-22 23:33 UTC, askulkarni2 commented
> Do you want to change the examples as well?

Done.

2022-02-23 10:44 UTC, vara-bonthu approved these changes
LGTM

2022-02-23 10:44 UTC, merged