Update k8s_taints documentation and taints fixes
aws-samples/aws-eks-accelerator-for-terraform pull request #289
Opened 2022-02-23 23:51 UTC by naris-silpakit

### What does this PR do?

- Adds examples for k8_taints in the managed-node-group documentation files.
- Removes k8s_taints from examples that passed them into self-managed node groups as EKS only supports taints through [managed node groups](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html).
- Removes k8_taints local from the aws-eks-fargate-profile module `locals.tf` for the same reason as above, and it wasn't being used.

### Motivation

Addressing a [documentation request](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/205) for k8s_taints for managed node groups. Thanks for reporting this [schwichti](https://github.com/schwichti)!

### More

- [ ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

2022-02-24 00:17 UTC, askulkarni2 requested changes
we should add support for self-managed via kubelet args.

2022-02-24 00:53 UTC, naris-silpakit commented
> we should add support for self-managed via kubelet args.

Hoping to keep the changes minor for this PR as it just clarifies the current functionality. I can look into adding taint support for self-managed node groups via the kubelet args as a separate new feature PR.

2022-02-24 01:09 UTC, askulkarni2 approved these changes
Opened https://github.com/aws-ia/terraform-ssp-amazon-eks/issues/187 for self-managed support.

2022-02-26 00:55 UTC, kcoleman731 approved these changes

2022-02-26 00:55 UTC, merged

2022-03-20 17:28 UTC, vara-bonthu commented
Closing the issue since the PR is merged now.